name: CICD
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  analysis:
    name: Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: foundry-rs/foundry-toolchain@v1
      - name: Check Formatting
        run: forge fmt --check
